[project]
name = "neural-ir-expansion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "ir-datasets>=0.5.11",
    "pandas>=2.3.1",
    "ruff>=0.12.3",
]
